SET IDENTITY_INSERT Marca ON;
INSERT INTO Marca (id, nombre, descripcion) VALUES
(21, 'Red Bull', 'Bebidas energéticas'),
(22, 'Monster', 'Bebidas energéticas y refrescos'),
(23, 'Gatorade', 'Bebidas isotónicas'),
(24, 'Nestlé Waters', 'Agua embotellada y bebidas naturales'),
(25, 'Cadbury', 'Chocolate y productos de confitería'),
(26, 'Tropicana', 'Jugos y bebidas de fruta'),
(27, 'Tio rico', 'Helados y postres congelados'),
(28, 'Barilla', 'Pasta y productos alimenticios'),
(29, 'Dole', 'Frutas y verduras enlatadas'),
(30, 'Pringles', 'Papas fritas y snacks'),
(31, 'Sunkist', 'Bebidas de fruta y refrescos'),
(32, 'Pillsbury', 'Mezclas para hornear y productos de panadería'),
(33, 'Jack Daniel’s', 'Bebidas alcohólicas y whisky'),
(34, 'Smirnoff', 'Vodka y bebidas alcohólicas'),
(35, 'Mary', 'Harina Pan'),
(36, 'Quaker', 'Avena y productos de desayuno'),
(37, 'M&M’s', 'Chocolate y golosinas'),
(38, 'Starbucks', 'Café y bebidas de café'),
(39, 'Ben & Jerry’s', 'Helados y postres congelados'),
(40, 'Lipton', 'Tés y bebidas heladas'),
(41, 'Chiquita', 'Plátanos'),
(42, 'Dole', 'Frutas y verduras frescas'),
(43, 'Gallo', 'Arroz'),
(44, 'Matarazzo', 'Pastas'),
(45, 'Hellmanns', 'Mayonesa y aderezos'),
(46, 'Ariel', 'Detergente para la ropa'),
(47, 'Downy', 'Suavizante para la ropa'),
(48, 'Fairy', 'Lavavajillas'),
(49, 'Mr. Proper', 'Limpiador multiusos'),
(50, 'Pampers', 'Pañales y productos para bebés'),
(51, 'Oral-B', 'Cepillos de dientes y productos de higiene bucal'),
(52, 'Gillette', 'Cuchillas de afeitar y productos de afeitado'),
(53, 'Johnsons', 'Productos de cuidado personal para bebés'),
(54, 'Scott', 'Papel higiénico y toallas de papel'),
(55, 'Duracell', 'Pilas'),
(56, 'Philips', 'Bombillas'),
(57, 'Harina PAN', 'Harina de maíz precocida'),
(58, 'Hallmark', 'Tarjetas de felicitación'),
(59, 'Raid', 'Insecticidas'),
(60, 'Miracle-Gro', 'Fertilizantes y tierra para macetas'),
(61, 'Fiskars', 'Herramientas de jardinería'),
(62, 'Kleenex', 'Pañuelos de papel y toallitas'),
(63, 'Kraft', 'Aderezos para ensaladas'),
(64, 'McCormick', 'Especias y hierbas secas'),
(65, 'Maggi', 'Caldos y sopas'),
(66, 'Fleischmanns', 'Levadura'),
(67, 'Royal', 'Gelatina y pudín'),
(68, 'Maní King', 'Mantequilla de maní'),
(69, 'Nutella', 'Chocolate para untar'),
(70, 'Natures Path', 'Semillas de girasol y frutas secas'),
(71, 'Del Monte', 'Frutas confitadas'),
(72, 'Ritz', 'Galletas saladas'),
(73, 'Pepperidge Farm', 'Palitos de pan'),
(74, 'Tostitos', 'Chips de tortilla'),
(75, 'Pace', 'Salsa para mojar'),
(76, 'Quaker', 'Galletas de arroz'),
(77, 'Equal', 'Edulcorantes artificiales'),
(78, 'Log Cabin', 'Sirope de arce'),
(79, 'Bertolli', 'Vinagre balsámico y vinagre de manzana'),
(80, 'Kikkoman', 'Salsa de soja'),
(81, 'Tabasco', 'Salsa picante'),
(82, 'Oscar Mayer', 'Jamón Serrano'),
(83, 'Altoids', 'Mentas'),
(84, 'Yankee Candle', 'Velas'),
(85, 'Bic', 'Bolígrafos'),
(86, 'Tylenol', 'Atamel'),
(87, 'Mi Granjero', 'Productos del campo y ganaderos'),
(88, 'El timon', 'Productos del mar'),
(89, 'Dog show', 'Alimento para perros'),
(90, 'Carmelos', 'Comida Congelada'),
(91, 'Santillana', 'Editorial');

SET IDENTITY_INSERT Marca OFF;