INSERT INTO ProductoRecomendadoParaProducto (productoId, productoRecomendadoId, mensaje) VALUES
(1, 40, 'Recomendado para mejorar tu compra.'),
(2, 41, 'Perfecto complemento para este producto.'),
(3, 42, 'No te lo pierdas.'),
(4, 43, 'Ideal para usar junto a este.'),
(5, 44, 'Aumenta tu experiencia con este.'),
(6, 45, 'Una excelente adición.'),
(7, 46, 'Maximiza tu satisfacción.'),
(8, 47, 'Complementa tu selección.'),
(9, 48, 'Un gran aliado para este producto.'),
(10, 49, 'No olvides agregarlo a tu carrito.'),
(11, 50, 'Aprovecha esta recomendación.'),
(12, 51, 'Un must-have para tu compra.'),
(13, 52, 'Ideal para completar tu pedido.'),
(14, 53, 'Gran opción para combinar.'),
(15, 54, 'Recomendado por nuestros expertos.'),
(16, 55, 'Mejora tu experiencia con esto.'),
(17, 56, 'Un producto que va de la mano.'),
(18, 57, 'No te quedes sin él.'),
(19, 58, 'Un complemento perfecto.'),
(20, 59, 'Te encantará este producto adicional.'),
(21, 60, 'La elección perfecta para complementar.'),
(22, 61, 'No puedes dejarlo pasar.'),
(23, 62, 'Recomendado para un uso óptimo.'),
(24, 63, 'Aumenta el valor de tu compra.'),
(25, 64, 'No olvides incluirlo en tu pedido.'),
(26, 65, 'Suma valor a tu compra.'),
(27, 66, 'Una recomendación que no te arrepentirás.'),
(28, 67, 'Un gran apoyo para tu elección.'),
(29, 68, 'Ideal para usuarios exigentes.'),
(30, 69, 'Complementa perfectamente tu selección.'),
(31, 70, 'Una recomendación segura.'),
(32, 71, 'El complemento ideal.'),
(33, 72, 'No te arrepentirás de elegirlo.'),
(34, 73, 'Una excelente elección adicional.'),
(35, 74, 'Maximiza tu satisfacción con esto.'),
(36, 75, 'Recomendado para un mejor rendimiento.'),
(37, 76, 'Un producto que no puede faltar.'),
(38, 77, 'Ideal para tus necesidades.'),
(39, 78, 'Una combinación ganadora.'),
(40, 79, 'Recomendado por nuestros clientes.'),
(40, 80, 'No olvides agregarlo para mejores resultados.');